version: '3'
services:
  app:
    container_name: platform
    restart: always
    build: .
    ports:
      - '7070:7070'
    depends_on:
      - 'mongo'
    volumes:
      - ticketSS:/usr/src/app/public/ticketSS
      - avatars:/usr/src/app/public/avatars
  mongo:
    container_name: mongo_platform
    restart: always
    image: mongo:4.1.8-xenial
    command: mongod --config /data/configdb/mongodb.conf
    ports: 
     - '27018:27018'
    volumes:
     - mongo-config:/data/configdb
     - mongoData:/data/db            
volumes:
  mongo-config:
  ticketSS:
  avatars:
  mongoData:
    external:
      name: mongo_external