version: '3'
services:
  app:
    container_name: platform
    restart: always
    build: .
    ports:
      - '7070:7070'
    depends_on:
      - 'mongo'
    volumes:
      - ticketSS:/usr/src/app/public/ticketSS
      - avatars:/usr/src/app/public/avatars
  mongo:
    container_name: mongo_platform
    restart: always
    image: mongo:4.4.2
    # command: mongod --port 27017
    ports: 
     - '27017:27017'
    volumes:
     - db-data:/data/db
     - mongo-config:/data/configdb

volumes:
  db-data: 
  mongo-config:
  ticketSS:
  avatars: