version: '3'
services:
  app:
    container_name: platform
    restart: always
    build: .
    ports:
      - '7070:7070'
    depends_on:
      - 'mongo'
    volumes:
      - ticketSS:/usr/src/app/public/ticketSS
      - avatars:/usr/src/app/public/avatars
      - docs:/usr/src/app/public/docs
      - docimages:/usr/src/app/public/docimages
      - covers:/usr/src/app/public/covers
      - images:/usr/src/app/public/images
      - stickers:/usr/src/app/public/stickers
  mongo:
    container_name: mongo_platform
    restart: always
    image: mongo:4.1.8-xenial
    command: mongod --auth --config /data/configdb/mongodb.conf
    ports: 
     - '27018:27018'
    volumes:
     - mongo-config:/data/configdb
     - mongoData:/data/db            
volumes:
  mongo-config:
  ticketSS:
  avatars:
  docs:
  docimages:
  covers:
  images:
  stickers:
  mongoData:
    external:
      name: mongo_external
