version: '3'
services:
  app:
    container_name: platform
    restart: always
    build: .
    ports:
      - '7070:7070'
    depends_on:
      - 'mongo'
    volumes:
      - ticketSS:/usr/src/app/public/ticketSS
      - avatars:/usr/src/app/public/avatars
  mongo:
    container_name: mongo_platform
    restart: always
    image: mongo:4.4.2
    # command: mongod --port 27017
    ports: 
     - '27017:27017'
    volumes:
     - db-data:/data/db
     - mongo-config:/data/configdb
  mongo-backup-local:
    image: futurice/docker-volume-backup
    volumes:
      - db-data:/backup/db-data:ro
      - ./../../../../../../../../../backups:/archive                  
  mongo-backup:
    container_name: mongo-backup
    image: tiredofit/mongodb-backup
    links:
     - mongo
    volumes:
      - backups:/backups
    environment:
      - DB_HOST=mongo
      - DB_DUMP_FREQ=720
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=2880
      - MD5=TRUE
      - COMPRESSION=GZ

    restart: always
volumes:
  db-data: 
  mongo-config:
  ticketSS:
  avatars:
  backups: